### ISSUE TITLE
Running tests correctly

### ISSUE THREAD

**Issue by CheukHinHoJerry** [pfnet-research/torch-dftd#24]
Hi,

Thank you for the nice package. I wonder where should I compile and put the `dftd3` module in order for the tests to run correctly. Could some minimal documentation be included? Or just a few lines in here educating me would be great.

Thank you.

**Comment by corochann** [comment]
Did you succeed installation of torch-dftd correctly?
https://github.com/pfnet-research/torch-dftd?tab=readme-ov-file#install

After that, you can type `pytest tests` in the terminal with the location on top of this repo's directory.
You can see detailed test command done in CI here.
https://github.com/pfnet-research/torch-dftd/blob/master/.flexci/pytest_script.sh#L22-L27

Maybe I'm not understanding your question well. If you could specify your questions more concretely, I might be able to answer more.

**Comment by CheukHinHoJerry** [comment]
Thank you for your reply - I am getting errors running `pytest tests` after installing torch-dftd successfully. Returned a bunch of 

```
FAILED tests/test_torch_dftd3_calculator.py::test_calc_energy[mol-bjm-b2-plyp-False] - FileNotFoundError: [Errno 2] No such file or directory: 'dftd3'
FAILED tests/test_torch_dftd3_calculator.py::test_calc_energy[mol-bjm-b3-lyp-False] - FileNotFoundError: [Errno 2] No such file or directory: 'dftd3'
FAILED tests/test_torch_dftd3_calculator.py::test_calc_energy[mol-bjm-b97-d-False] - FileNotFoundError: [Errno 2] No such file or directory: 'dftd3'
FAILED tests/test_torch_dftd3_calculator.py::test_calc_energy[mol-bjm-b-lyp-False] - FileNotFoundError: [Errno 2] No such file or directory: 'dftd3'
FAILED tests/test_torch_dftd3_calculator.py::test_calc_energy[mol-bjm-b-p-False] - FileNotFoundError: [Errno 2] No such file or directory: 'dftd3'
FAILED tests/test_torch_dftd3_calculator.py::test_calc_energy[mol-bjm-pbe-False] - FileNotFoundError: [Errno 2] No such file or directory: 'dftd3'
FAILED tests/test_torch_dftd3_calculator.py::test_calc_energy[mol-bjm-pbe0-False] - FileNotFoundError: [Errno 2] No such file or directory: 'dftd3'
FAILED tests/test_torch_dftd3_calculator.py::test_calc_energy[mol-bjm-lc-wpbe-False] - FileNotFoundError: [Errno 2] No such file or directory: 'dftd3'
FAILED tests/test_torch_dftd3_calculator.py::test_calc_energy[mol-zerom-b2-plyp-False] - FileNotFoundError: [Errno 2] No such file or directory: 'dftd3'
FAILED tests/test_torch_dftd3_calculator.py::test_calc_energy[mol-zerom-b3-lyp-False] - FileNotFoundError: [Errno 2] No such file or directory: 'dftd3'
FAILED tests/test_torch_dftd3_calculator.py::test_calc_energy[mol-zerom-b97-d-False] - FileNotFoundError: [Errno 2] No such file or directory: 'dftd3'
FAILED tests/test_torch_dftd3_calculator.py::test_calc_energy[mol-zerom-b-lyp-False] - FileNotFoundError: [Errno 2] No such file or directory: 'dftd3'
```

which I guess I am not compiling the ase dftd3 calculator correct? I am genuinely uncertain about that and would be great if you could help me out.

**Comment by corochann** [comment]
Ah I see.
In the test, we check that our output value is same with the original DFTD3 implementation. So you need to install original DFTD3. Please refer below for the installation command:
https://github.com/pfnet-research/torch-dftd/blob/master/docker/Dockerfile#L35-L41

**Comment by CheukHinHoJerry** [comment]
Ah i see - I think the reason is that i didn't `mv dft3` to `/usr/local/bin` and set the environment paths correctly. I will test it later and close the issue if I get this fixed. Thank you.

**Comment by CheukHinHoJerry** [comment]
Perfect - thank you for highlighting that to me. Works out of the box.
